- CONTRIBUTING.md
This should help newcomers who occasionally open issues that aren’t bug reports or feature requests.
> Add note about purpose of GitHub issues to CONTRIBUTING.md.

- README.md
Currently, the subject of the readme's last sentence is "D3's emphasis," which is bit abstract for a subject. Foregrounding D3 and having it as the main actor would make the sentence stronger and clearer.
Additionally, the adverbial clause (begins with "combing...") is a little odd. I moved this adverbial clause to the beginning to clarify the relationship between "combining" and "D3." Currently, the clause is modifying the verb "gives," but placing it after "framework" makes it seem like its actually modifying "framework." 
In any case, I just felt that the last sentence was a little long and odd, so I'm proposing these changes and hoping that you find them helpful.
> Changed subject of last sentence to be D3.

- src/selection/data.js
- test/selection/data-test.js
If a selection is missing elements, then selection.data would still attempt to evaluate the optional key function for the missing elements, resulting in an uncaught TypeError. For example:
```js
d3.selectAll("p")
.select(function(d, i) { return i & 1 ? this : null; })
.data([1, 2, 3], Number);
```
Now, any missing elements are automatically assigned to the exit selection.
> Fix for null node in selection.data.

- src/layout/chord.js
- (x - x0) / k sometimes provides a value with trailing 0's due to division. This means groups that have an integer value appear to be a decimal number
Example of problem below:
With changes:
> Remove trailing 0 error from chord group value

- package.json
if we want to define a different entry point for browserify, we should be using the browser key: https://github.com/substack/node-browserify#browser-field
The browserify key in package.json should be an object that is used to define globalt transforms: 
https://github.com/substack/node-browserify#browserifytransform
This fix will allow d3 to be used through cartero (https://github.com/rotundasoftware/cartero) which relies on browserify for creating bundles
Thanks!
F
> Fix browserify key in package.json

- src/geo/point-in-polygon.js
Hi!
I was hit by what seems to be #2025 when developing a couple of canvas-based maps. This change fixes it for me.
I have no idea if this is correct or makes any sense in general, but I have not found any regressions so far.
Thank you,
Lukas
> Possible fix for #2025, handle zero-area polygons better

- CHANGES.md
I was reading through this and it seemed like you meant "inspected" here:
* before: "...that also allows the axis tick arguments to be inspect."
* after: "...that also allows the axis tick arguments to be **inspected**".
> to be inspect -> to be inspected

- API.md
`Local Variables` API description is incorrect.
> Fixed description typo in API reference.

- CHANGES.md
- README.md
According to the [creator's twitter](https://twitter.com/mjackson/status/770427936449101824) and the [npmcdn's website](https://npmcdn.com/) the project was renamed to unpkg to avoid trademark issues.
> Updated npmcdn.com links to unpkg.com

- API.md
Duplicated utcFormat entries on API reference. Fixed wrong one.
> Fixed typo in API reference

- API.md
A few typos in the anchors for links in API.md:
"axisTight" -> "axisRight"
"axisTeft" -> "axisLeft"
> Correct typos in d3-axis documentation

- API.md
Super tiny change in documentation. 
Looks like the functionality of color.toString changed between v3 and v4. v3 returned hex representation and v4 returns string according to CSS spec. But, this description got missed in the md file. 
I wasn't sure if you'd prefer "returns string representation of rbg values" or "returns string according to CSS spec" or something else. Mostly just wanted to flag the need for this tweak in the documentation. 
thanks!
> Update desc of color.toString to match v4 functionality

- API.md
Change all `radialLine` to `lineRadial`.
Also add `density.size`, `link.context` and `d3.pointRadial`.
"Streams" header should be a _h3_ and not a _h4_.
> API.md: radialLine must be lineRadial

- README.md
The API Reference link at the top of README.md used "master" instead of "main". GitHub would redirect to the correct page, but with a warning message.
> Updated API Reference Link in README.md

- docs/getting-started.md
I know you removed the TODO but I was already trying to fill it in! I think just making the distinction of modules that touch the DOM and those that don't was super clarifying for me personally when I figured that out. And I always forget the most basic ref pattern (and still might've messed it up here). I don't think we should get into updating or interactivity or whatever, but I think just this much goes a long way toward demystifying (and showing just the most basic best practices).
> Add short "D3 in React" section

- docs/getting-started.md
Not sure about the exact phrasing but I think something like this would be nice. It'd be overwhelming to list every module that touches the DOM, but it may be frustratingly vague to just say "most don't, some do". Is there a general principle by which the uninitiated reader might spot which do and don't? As a beginner programmer learning D3 I know I didn't have a good mental model of where the DOM fit in, but I think I'd at least be able to spot "does this take a selection".
> State a general principle for which d3 modules compete with React

- docs/d3-time.md
- Add missing date arguments to `d3.timeMonth.floor()` and `d3.timeMonth.ceil()` calls.
- Fix the expected date range
> Fix d3-time example

- docs/d3-force/link.md
- docs/d3-force/simulation.md
> add mutation warnings

- docs/getting-started.md
add an example of how to load from a single module (using the recommended ESM method & destructuring)
> single module

- docs/.vitepress/config.ts
- docs/.vitepress/theme/CustomFooter.vue
- docs/community.md
Replaces temporary Slack invite links with a static redirect to the latest invite URL that can be updated independently.
> Update Slack invite links

- docs/d3-scale/time.md
use scaleTime in the d3.scaleTime example (the results are unchanged since the domain is specified).
> scaleTime example

- docs/getting-started.md
JSX uses `camelCase` convention for props names. 
Updated `stroke-width` accordingly in React code samples.
[React support for SVG components](https://react.dev/reference/react-dom/components#all-svg-components)
> Fix svg syntax for JSX code samples in getting-started with React

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- docs/api.md
- docs/d3-scale-chromatic/categorical.md
- yarn.lock
by @pettiross 
ref. https://github.com/d3/d3-scale-chromatic/pull/51
ref. https://github.com/observablehq/plot/pull/1895
[![scheme](https://github.com/d3/d3-scale-chromatic/assets/7001/24bf1319-28b6-4b1a-9db2-dd7e92023b39)](https://observablehq.com/@d3/scheme-observable10)
> documentation for schemeObservable10

- docs/d3-polygon.md
The example under the `polygonCentroid` heading was calling `polygonArea`.
> docs: fix typo in polygonCentroid example

- docs/getting-started.md
Added a Github link to the "DefinitelyTyped" in the "Installing from npm" section of the Getting Started page.
> Added a Github link to the DefinitelyTyped

- docs/d3-shape/pie.md
Fixed a typo in [docs/d3-shape/pie.md](https://d3js.org/d3-shape/pie#pie_sortValues). The example code for `pie.sortValues` in the docs referred to `.sortValue` instead of `.sortValues`.
> Fixed example pie.sortValues code in docs

- docs/components/ExampleAnimatedQuadtree.vue
- docs/components/ExampleChord.vue
- docs/components/ExampleCollideForce.vue
- docs/components/ExampleDisjointForce.vue
- docs/components/ExampleLinkForce.vue
- docs/d3-contour.md
- docs/d3-drag.md
- docs/d3-force.md
- docs/d3-force/link.md
- docs/d3-geo/azimuthal.md
- docs/d3-geo/conic.md
- docs/d3-geo/cylindrical.md
- docs/d3-hierarchy/partition.md
- docs/d3-hierarchy/treemap.md
- docs/d3-scale/quantize.md
- docs/d3-shape/arc.md
- docs/d3-shape/area.md
- docs/d3-shape/line.md
- docs/d3-shape/pie.md
- docs/d3-shape/stack.md
- docs/getting-started.md
Removes the `?intent=fork`, suppressing the green fixed banner at the top of notebooks to give a cleaner presentation of the notebook.
> remove ?intent=fork

- docs/.vitepress/config.ts
Changed the `utm_source` string for the page navigation to Examples to distinguish if from the link on the home page.
> changed utm_source for examples link

- docs/.vitepress/config.ts
- docs/index.md
In order for us to track referrals from d3js.org to observablehq.com, we need to add rel = "external" to the links from Vitepress's buttons and navigation.
> add rel external to observablehq links

- docs/getting-started.md
The **D3 in Svelte** section have a broken link to the Svelte playground (REPL). 
This PR updates the url to the new one.
> Update getting-started.md link to Svelte example
